"""Generate the minimal production .env without overwriting an existing file."""

from __future__ import annotations

import argparse
import os
import secrets
from pathlib import Path
from urllib.parse import urlsplit


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Report Analysis production secrets")
    parser.add_argument(
        "--base-url",
        default="http://localhost:8000",
        help="Public origin, for example https://reports.example.com",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / ".env",
        help="Destination .env path",
    )
    return parser.parse_args()


def validate_origin(value: str) -> str:
    origin = value.rstrip("/")
    parsed = urlsplit(origin)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        raise SystemExit("--base-url must be a valid http:// or https:// origin")
    if parsed.path or parsed.query or parsed.fragment or parsed.username or parsed.password:
        raise SystemExit("--base-url cannot contain a path, query, fragment, or credentials")
    return origin


def main() -> None:
    args = parse_args()
    output = args.output.resolve()
    if output.exists():
        raise SystemExit(f"Refusing to overwrite existing file: {output}")

    base_url = validate_origin(args.base_url)
    password = secrets.token_urlsafe(18)
    session_secret = secrets.token_urlsafe(48)
    encryption_key = secrets.token_urlsafe(48)
    content = "\n".join(
        [
            "# Generated by scripts/generate_env.py — do not commit",
            "APP_ENV=production",
            "APP_BIND_ADDRESS=127.0.0.1",
            "APP_PORT=8000",
            f"APP_BASE_URL={base_url}",
            f"FRONTEND_URL={base_url}",
            f"ALLOWED_ORIGINS={base_url}",
            f"FB_REDIRECT_URI={base_url}/api/facebook/oauth/callback",
            f"APP_AUTH_PASSWORD={password}",
            f"APP_SESSION_SECRET={session_secret}",
            f"TOKEN_ENCRYPTION_KEY={encryption_key}",
            "FB_GRAPH_API_VERSION=v25.0",
            "FB_APP_ID=",
            "FB_APP_SECRET=",
            "ANTHROPIC_API_KEY=",
            "ANTHROPIC_MODEL=claude-sonnet-4-6",
            "",
        ]
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor = os.open(output, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as env_file:
        env_file.write(content)

    print(f"Created {output}")
    print(f"Workspace password: {password}")
    print("Keep this file secret and back it up together with the Docker volume.")


if __name__ == "__main__":
    main()
